CREATE TABLE IF NOT EXISTS mrwg_registrations (
  id SERIAL PRIMARY KEY,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  full_name TEXT NOT NULL,
  guardian_name TEXT NOT NULL,
  dob DATE NOT NULL,
  gender TEXT NOT NULL,
  cnic TEXT NOT NULL,
  mobile TEXT NOT NULL,
  whatsapp TEXT,
  email TEXT NOT NULL,
  qualification TEXT NOT NULL,
  specialization TEXT NOT NULL,
  institution TEXT NOT NULL,
  designation TEXT NOT NULL,
  membership_category TEXT NOT NULL,
  amount_paid TEXT,
  registration_fee TEXT,
  payment_method TEXT,
  payment_method_other TEXT,
  transaction_id TEXT,
  payment_date DATE,
  paid_by TEXT,
  payment_screenshot_url TEXT,
  areas_of_interest JSONB,
  areas_of_interest_other TEXT,
  how_heard TEXT,
  declaration_accepted BOOLEAN NOT NULL DEFAULT false,
  signature TEXT NOT NULL
);
